---
title: "Introduction to data analysis with R"
description: |
  Heidelberg University, Biochemistry Bachelor and Master (WS 19/20)
author:
  - name: Jannik Buhr 
date: 10-20-2020
output:
  distill::distill_article:
    self_contained: false
---

## Informationen

Der Kurs wird zwei Mal angeboten: Ab dem 18. Oktober 2019 für Bachelorstudierende
([link zum Vorlesungsverzeichnis](https://lsf.uni-heidelberg.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=299344&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung))
und ab dem 10. Januar 2020 für Masterstudierende
([link zum Vorlesungsverzeichnis](https://lsf.uni-heidelberg.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=306025&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung)).
In beiden Kursen werden die selben Konzepte vermittelt aber die Beispiele auf das jeweilige Publikum
und das Tempo an eventuelle Vorkenntnisse angepasst. In den vergangenen Jahren wurde der Kurs nur für
den Bachelor angeboten und hieß noch _Bioinformatik / Statistik_, wurde nun aber wie ursprünglich
geplant umbenannt. Das Kurskonzept der Dozentin der letzten Jahre, Dr. Johanna Schott, habe ich
zu großen Teilen überarbeitet. Da Programmierkonzepte und Kniffe in R sich schneller
weiterentwickeln als die eher zeitlosen mathematischen und statistischen Konzepte bezieht sich
diese Überarbeitung vorallem auf das Erstgenannte.

Wer also bereits im Bachelor den Kurs in seiner alten Form besucht hat ist dennoch eingeladen, nocheinmal
teilzunehmen um die neusten Konzepte und Tricks bei der Auswertung von Daten kennenzulernen und
auszuprobieren.

## Anmeldung

Damit ich euch während des Kurses mit Informationen versorgen kann
schickt mir bitte eine e-Mail über mein [Kontaktformular](/#contact) auf dieser Webseite. Bitte schreibt
dabei neben eurem Namen auch, ob ihr euch auf den Bachelor- oder Masterkurs bezieht.

## Vorbereitung

Für den Kurs wird eine Installation von R sowie RStudio benötigt, die ihr
jeweils frei verfügbar unter den folgenden Links herunterladen könnt:

- [Download R](https://cran.uni-muenster.de/)
- [Download RStudio](https://www.rstudio.com/products/rstudio/download/#download)

## Materialien

Alle Materialien, die ihr für den Kurs benötigt und die wir im Laufe des Kurses erarbeiten werden findet ihr [unter diesem link](/books/dataIntro19).

Die Materialien für den master Kurs auf Englisch finden sich [unter diesem link](/books/dataIntro19Master).

Zusätzliche Vorlesungs-Slides finden sich [hier](/slides/dataintro19).

